name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        unset CI 
        npm run build
      env:
        REACT_APP_ORG_NAME: ${{ secrets.REACT_APP_ORG_NAME }}
        REACT_APP_ACCESS_TOKEN: ${{ secrets.REACT_APP_ACCESS_TOKEN }}

    - name: Deploy
      run: |
        unset CI
        npm run deploy
