name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Deploy
      run: |
        unset CI
        git config --global user.email adityasingh27@hotmail.com
        git config --global user.name Aditya
        npm install
        npm run deploy
      env:
        REACT_APP_ORG_NAME: ${{ secrets.REACT_APP_ORG_NAME }}
        REACT_APP_ACCESS_TOKEN: ${{ secrets.REACT_APP_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.REACT_APP_ACCESS_TOKEN }}
