name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run build
      env:
        REACT_APP_ORG_NAME: ${{ secrets.REACT_APP_ORG_NAME }}
        REACT_APP_ACCESS_TOKEN: ${{ secrets.REACT_APP_ACCESS_TOKEN }}

    - name: Deploy
      run: |
        git config --global user.email ${{ secrets.EMAIL }}
        git config --global user.name ${{ secrets.USERNAME }}
        git remote set-url origin https://github.com/Block-Exchange/web.git
        npm run deploy
